name: meu_apoio
description: "App com reconhecimento de voz e integração com IA (Wit.ai)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  device_apps: ^2.2.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.5
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0
  url_launcher: ^6.3.0
  http: ^1.2.1 
  intl: ^0.20.2
  permission_handler: ^12.0.0+1
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
